# Generated by Django 3.2.8 on 2023-03-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
