# Generated by Django 3.2.8 on 2023-03-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('integrantes', models.IntegerField()),
                ('nombre_equipo', models.CharField(blank=True, max_length=300, null=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.convocatoria')),
            ],
        ),
    ]
