# Generated by Django 3.2.8 on 2023-03-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonmbre_equipo', models.CharField(max_length=100)),
                ('captain_id', models.IntegerField()),
                ('participant1', models.CharField(max_length=300)),
                ('participant2', models.CharField(max_length=300)),
                ('participant3', models.CharField(max_length=300)),
                ('participant4', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
    ]
